[build]
nixPkgs = ["python311", "python311Packages.pip", "libGL", "libGLU", "mesa"]

[phases.install]
cmds = [
  "python -m venv /app/venv",
  "/app/venv/bin/pip install --upgrade pip",
  "/app/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/app/venv/bin/gunicorn app:app --bind 0.0.0.0:8080"
