[build]
nixPkgs = ["python311", "python311Packages.pip", "libGL", "libGLU", "mesa"]

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "libGL", "libGLU", "mesa"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:8080"
